### PR TITLE
[css-logical-properties-1] Add test case for {inline-,block-}size

### PR DESCRIPTION
**Pull request by axinging**
Spec is here: https://drafts.csswg.org/css-logical-props-1/.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1165)

### CODE REVIEW

**Comment by axinging** [comment]
@rune-opera @cbiesinger, PTAL

**Comment by cbiesinger** [comment]
Could you fix the missing anchors that syncbot commented on? Thanks!

**Comment by axinging** [comment]
@cbiesinger  done, ths.

**Comment by rune-opera** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[css-logical-properties-1/logicalprops-block-size-vlr.html, line 129 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YiUHzEcNNTCX3oaPj:-K_YiUI2YF3Wasu0uqlh:bdm54ff) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size-vlr.html#L129)):*
> ```HTML
> <p id="p2">Hello, this is a test</div>
> <p id="ref_p1">Hello, this is a test</div>
> <p id="ref_p2">Hello, this is a test</div>
> ```

If the "Hello ..." text is not relevant to the test, just remove it.

---

*[css-logical-properties-1/logicalprops-block-size.html, line 125 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YijXEfphjmHSn9Rhu:-K_YijXEfphjmHSn9Rhv:bxnistc) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size.html#L125)):*
> ```HTML
> <p id="p2">Hello, this is a test</div>
> <p id="ref_p1">Hello, this is a test</div>
> <p id="ref_p2">Hello, this is a test</div>
> ```

Remove "Hello ..." text

---

*[css-logical-properties-1/logicalprops-block-size.html, line 151 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ZXqdxnhi2neDcYsxF:-K_ZXqdxnhi2neDcYsxG:b-lkxde2) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size.html#L151)):*
> ```HTML
>   assert_true(compareWidthHeight("div2","ref_div2"));
>   assert_true(compareWidthHeight("div3","ref_div3"));
> }, "Check that block-size < min-block-size or min-block-size< block-size <=max-block-size or block-size > max-block-size");
> ```

Nit: I would have put spaces on both sides of the comparative operators in the text above.

---

*[css-logical-properties-1/logicalprops-inline-size-vlr.html, line 129 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YinTlBT5GcuHmU_FM:-K_YinTlBT5GcuHmU_FN:bj4z706) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size-vlr.html#L129)):*
> ```HTML
> <p id="p2">Hello, this is a test</div>
> <p id="ref_p1">Hello, this is a test</div>
> <p id="ref_p2">Hello, this is a test</div>
> ```

Remove "Hello ... " text

---

*[css-logical-properties-1/logicalprops-inline-size-vlr.html, line 168 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_Po2TyEl817aBZSGdE:-K_Po2TyEl817aBZSGdF:bggiqk1) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size-vlr.html#L168)):*
> ```HTML
> }, "Check that inline-size < min-inline-size or min-inline-size< inline-size <=max-inline-size or inline-size > max-inline-size in table vertical-lr");
> </script>
> </script>
> ```

Duplicate end-tag?

---

*[css-logical-properties-1/logicalprops-inline-size.html, line 68 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_Z_NtrKRW2q40VQ1FP:-K_Z_NtrKRW2q40VQ1FQ:bgbm2j) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size.html#L68)):*
> ```HTML
>   display: table;
> }
> .tablecolumn {
> ```

As table columns is a different thing, I would have called this .tablecell and #table1_column -> #table1_cell etc to avoid confusion.

---

*[css-logical-properties-1/logicalprops-inline-size.html, line 125 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YivxIjU-8q0FPul1_:-K_YivxIjU-8q0FPul1a:bj4z706) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size.html#L125)):*
> ```HTML
> <p id="p2">Hello, this is a test</div>
> <p id="ref_p1">Hello, this is a test</div>
> <p id="ref_p2">Hello, this is a test</div>
> ```

Remove "Hello ... " text

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
@rune-opera, done, ths.

**Comment by axinging** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[css-logical-properties-1/logicalprops-block-size-vlr.html, line 129 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YiUHzEcNNTCX3oaPj:-K_aqgAuOxsDbjnBP-xa:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size-vlr.html#L129)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

If the "Hello ..." text is not relevant to the test, just remove it.
</blockquote></details>

Done.

---

*[css-logical-properties-1/logicalprops-block-size.html, line 125 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YijXEfphjmHSn9Rhu:-K_aqi4bMYPUz5KfFxvA:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size.html#L125)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

Remove "Hello ..." text
</blockquote></details>

Done.

---

*[css-logical-properties-1/logicalprops-block-size.html, line 151 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ZXqdxnhi2neDcYsxF:-K_aqsx4VKDJPqEnMcct:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size.html#L151)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

Nit: I would have put spaces on both sides of the comparative operators in the text above.
</blockquote></details>

Done.

---

*[css-logical-properties-1/logicalprops-inline-size-vlr.html, line 129 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YinTlBT5GcuHmU_FM:-K_aquWF49ysqe1YwEEc:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size-vlr.html#L129)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

Remove "Hello ... " text
</blockquote></details>

Done.

---

*[css-logical-properties-1/logicalprops-inline-size-vlr.html, line 168 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_Po2TyEl817aBZSGdE:-K_aqzyNWyvpo5zvD5f1:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size-vlr.html#L168)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

Duplicate end-tag?
</blockquote></details>

Done.

---

*[css-logical-properties-1/logicalprops-inline-size.html, line 68 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_Z_NtrKRW2q40VQ1FP:-K_ar1_RAaiBXuFSf0fE:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size.html#L68)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

As table columns is a different thing, I would have called this .tablecell and #table1_column -> #table1_cell etc to avoid confusion.
</blockquote></details>

Done.

---

*[css-logical-properties-1/logicalprops-inline-size.html, line 125 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YivxIjU-8q0FPul1_:-K_ar2h7KYgp8-xyk1Rh:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size.html#L125)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

Remove "Hello ... " text
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
@cbiesinger @rune-opera 
Follow Timothy Loh's suggestion, add quirky length related case. 
Spec is here: 
https://quirks.spec.whatwg.org/#the-unitless-length-quirk

**Comment by rune-opera** [comment]
Reviewed 3 of 4 files at r2, 4 of 4 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[css-logical-properties-1/logicalprops-block-size-quirklength-vlr.html, line 64 at r3](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_cdj1k5GvUvDOqE3KK:-K_cdj1k5GvUvDOqE3KL:bvajmj8) ([raw file](https://github.com/w3c/csswg-test/blob/e70314d4fd51048915d03859af8a50b9c8ea5675/css-logical-properties-1/logicalprops-block-size-quirklength-vlr.html#L64)):*
> ```HTML
>   assert_true(compareWidthHeight("div4", "ref_div4"));
> }, "Check that block-size with quirky length in vertical-lr");
> </script>
> ```

This is more elaborate than it needs to be. You can test this at the parsing level. Just make the quirks tests into a single file testing that declarations with quirky lengths are dropped by checking the cssom.

---

*[css-logical-properties-1/logicalprops-block-size-vlr.html, line 129 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YiUHzEcNNTCX3oaPj:-K_cdS4e-ZIt4f75rVi0:b7asnmr) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size-vlr.html#L129)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove all text

---

*[css-logical-properties-1/logicalprops-block-size.html, line 125 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YijXEfphjmHSn9Rhu:-K_cdPSb1dMLqUW13kyG:bd7c6p7) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-block-size.html#L125)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove all text.

---

*[css-logical-properties-1/logicalprops-inline-size-vlr.html, line 129 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YinTlBT5GcuHmU_FM:-K_cd7DU8KTG-hFHdRgN:b-5hhg90) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size-vlr.html#L129)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove all the text.

---

*[css-logical-properties-1/logicalprops-inline-size.html, line 125 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_YivxIjU-8q0FPul1_:-K_ccinNpJI5lGEGdYTY:bq3iv5k) ([raw file](https://github.com/w3c/csswg-test/blob/9eb83a3490f67a387ec87fbf100a50be46fd82c4/css-logical-properties-1/logicalprops-inline-size.html#L125)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant that you could remove all of the text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by rune-opera** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
Review status: 1 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[css-logical-properties-1/logicalprops-block-size-quirklength-vlr.html, line 64 at r3](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_cdj1k5GvUvDOqE3KK:-K_gIQnq5DNFKYP7LzmG:brelvnc) ([raw file](https://github.com/w3c/csswg-test/blob/e70314d4fd51048915d03859af8a50b9c8ea5675/css-logical-properties-1/logicalprops-block-size-quirklength-vlr.html#L64)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

This is more elaborate than it needs to be. You can test this at the parsing level. Just make the quirks tests into a single file testing that declarations with quirky lengths are dropped by checking the cssom.
</blockquote></details>

Merged into one. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by rune-opera** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 167 at r4](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_im2Vv9_qCtUtLVjB6:-K_inPzwX4aaBmRGnTPJ:b-aa0wsk) ([raw file](https://github.com/w3c/csswg-test/blob/12b2ec4aaad72a514012b14b1f08d668befed1f5/css-logical-properties-1/logicalprops-quirklength.html#L167)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

This is still too complicated, I think. Something like this should suffice:

<style>
    #dummy {}
</style>
<script>
    function isValidDeclaration(cssText) {
        var cssRule = document.styleSheets[0].cssRules[0];
        cssRule.style = cssText;
        var valid = (cssRule.style.length > 0);
        cssRule.style = "";
        return valid;
    }

    test(() => assert_false(isValidDeclaration("block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("min-block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("max-block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("inline-size: 1")), "");
    test(() => assert_false(isValidDeclaration("min-inline-size: 1")), "");
    test(() => assert_false(isValidDeclaration("max-inline-size: 1")), "");

</blockquote></details>

Another try:

```
<style>
    #dummy {}
</style>
<script>
    function isValidDeclaration(cssText) {
        var cssRule = document.styleSheets[0].cssRules[0];
        cssRule.style = cssText;
        var valid = (cssRule.style.length > 0);
        cssRule.style = "";
        return valid;
    }

    test(() => assert_false(isValidDeclaration("block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("min-block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("max-block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("inline-size: 1")), "");
    test(() => assert_false(isValidDeclaration("min-inline-size: 1")), "");
    test(() => assert_false(isValidDeclaration("max-inline-size: 1")), "");
</script>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 167 at r4](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_im2Vv9_qCtUtLVjB6:-K_lEqbZOca-3SY-a32G:b-qsvnoa) ([raw file](https://github.com/w3c/csswg-test/blob/12b2ec4aaad72a514012b14b1f08d668befed1f5/css-logical-properties-1/logicalprops-quirklength.html#L167)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

Another try:

```
<style>
    #dummy {}
</style>
<script>
    function isValidDeclaration(cssText) {
        var cssRule = document.styleSheets[0].cssRules[0];
        cssRule.style = cssText;
        var valid = (cssRule.style.length > 0);
        cssRule.style = "";
        return valid;
    }

    test(() => assert_false(isValidDeclaration("block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("min-block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("max-block-size: 1")), "");
    test(() => assert_false(isValidDeclaration("inline-size: 1")), "");
    test(() => assert_false(isValidDeclaration("min-inline-size: 1")), "");
    test(() => assert_false(isValidDeclaration("max-inline-size: 1")), "");
</script>
```

</blockquote></details>

Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 1 at r4](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ilKzVrhvisHwI7tJd:-K_lF0TPxguB4jz02KZV:b-qsvnoa) ([raw file](https://github.com/w3c/csswg-test/blob/12b2ec4aaad72a514012b14b1f08d668befed1f5/css-logical-properties-1/logicalprops-quirklength.html#L1)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

This triggers strict mode, you need to test quirks in quirks mode. I don't know if tests typically use a known quirks doctype or just leaves it out with a comment. Check if there are other quirks tests in the repo and see what they do.
</blockquote></details>

Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by rune-opera** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 28 at r5](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ne1w3TtDbB0VUa7yw:-K_ne1w3TtDbB0VUa7yx:btb7wi) ([raw file](https://github.com/w3c/csswg-test/blob/25e8202c4235dae7127ee449500ee25c577fa7d8/css-logical-properties-1/logicalprops-quirklength.html#L28)):*
> ```HTML
> ];
> tests.forEach(function(t) {
>   test(() => assert_false(isValidDeclaration(t.cssText)), "");
> ```

The test description should not be empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 28 at r5](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ne1w3TtDbB0VUa7yw:-K_nosrF6k1uqhJ2gPpk:bevftus) ([raw file](https://github.com/w3c/csswg-test/blob/25e8202c4235dae7127ee449500ee25c577fa7d8/css-logical-properties-1/logicalprops-quirklength.html#L28)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

The test description should not be empty.
</blockquote></details>

Done, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by rune-opera** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 28 at r5](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ne1w3TtDbB0VUa7yw:-K_npxUJDE2L2LGzh_oS:b1wsuhc) ([raw file](https://github.com/w3c/csswg-test/blob/25e8202c4235dae7127ee449500ee25c577fa7d8/css-logical-properties-1/logicalprops-quirklength.html#L28)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

Done, PTAL.
</blockquote></details>

How about: "Check that unitless lengths are not valid for logical properties in quirks mode."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by axinging** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[css-logical-properties-1/logicalprops-quirklength.html, line 28 at r5](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-K_ne1w3TtDbB0VUa7yw:-K_ntHNnXnlmyDRQVWXf:bwna65e) ([raw file](https://github.com/w3c/csswg-test/blob/25e8202c4235dae7127ee449500ee25c577fa7d8/css-logical-properties-1/logicalprops-quirklength.html#L28)):*
<details><summary><i>Previously, rune-opera (Rune Lillesveen) wrote…</i></summary><blockquote>

How about: "Check that unitless lengths are not valid for logical properties in quirks mode."
</blockquote></details>

Yes, it's more clear. Done, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by rune-opera** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165)*

**Comment by rune-opera** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1165#-:-K_ntoa_XaYvkyhmkEj0:bnfp4nl)*

**Pull request merged**
