### PR TITLE
[css-ui-3] Add tests for text-overflow

### PR DESCRIPTION
**Pull request by frivoal**
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1196)

### CODE REVIEW

**Comment by fantasai** [comment]
So, my initial set of comments here is that most of your tests are optimized to make a green square at a great cost to understandability. It's definitely nice to share common references. Going a little out of your way to do so is fine. But making a test so convoluted that it is 10x more difficult to understand is not an acceptable cost to doing so. Please re-review your green square tests and rewrite as needed.

A few comments on the non-square tests:
* 019 says “are selected” ... there are two things to check here -- one is whether they appear highlighted, the other is whether they will copy when a copy command is initiated. You need to check both, explicitly.
* 021 needs shorter text, as it currently overflows (due to scrollbars taking up space). I would recommend merely using the word PASS, which is traditional for such things, and using a left margin instead of space characters to ensure that the word PASS is positioned “offscreen”.
* 018 is a pretty good test, but I'm finding it quite difficult in Firefox to actually select everything in the box. It seems to work if I select from above+left of the top left corner to below+right of the bottom right corner, but as there isn't much space for the cursor there without running into other pieces of the test (like the textarea), I'd suggest increasing the margin/border/padding to make that easier. Insufficient scope in the selection drag results in copying out pieces of the elided text rather than the whole thing. Alternately maybe that qualifies as a fail. I'm not sure.

**Review by fantasai — CHANGES_REQUESTED** [review]
[see above]

**Comment by frivoal** [comment]
@fantasai 

> Most of your tests are optimized to make a green square at a great cost to understandability. [...] Please re-review your green square tests and rewrite as needed.

They did not feel that convoluted when I wrote them, but re-reading after having had enough time to forget, I agree that it takes more effort to figure out what they do than it should. I'll review and rework them in that light.

> 018 is a pretty good test, but [...] Alternately maybe that qualifies as a fail. I'm not sure.

It qualifies as a fail. You are trying to select the whole elided text to see if it copy&pastes fine, while the spec says that selecting the ellipsis itself should select the elided text. Firefox doesn't do that, which is what makes selecting everything hard. so it's a fail. Do you think it would be enough to clarify the text of the test to make it clear that you're only supposed to try and select the visible "...", or do you think deeper changes to the test are needed?

> 019 says “are selected” ... there are two things to check here -- one is whether they appear highlighted, the other is whether they will copy when a copy command is initiated. You need to check both, explicitly.

Hmm, not sure about that. The spec says "If all of the ellipsed text is selected, UAs should show selection of the ellipsis". If the whole text is selected, and the ellipsis is highlighted, and something doesn't copy, that certainly does not sound like a nice behavior, but I don't see which part of css-ui-3 it would violate. If `selectAllChildren()` fails to select everything, that sounds like a spec violation of the Selection API spec, but I am not testing that here. Based on that, I think the test is correct as is, maybe just with a rephrasing from "are selected" to "are highlighted" (or "appear selected" to avoid making assumptions about how UAs show that things are selected). No?

I suppose I could also write a text that checks that selectAllChildren is unaffected text-overflow, but that feels like something the Selection API spec should test.

> 021 needs shorter text

Fixed. It did fit when my OS was configured to use overlay scrollbars, but depending on that was wrong.

> and using a left margin instead of space characters to ensure that the word PASS is positioned “offscreen”.

I'm using a monospace font, and sizing things in ch, so the  word PASS is guaranteed to be "offscreen". After that, spaces vs left margin feels subjective, and I find the test easier to read with spaces, so I've left it as is for now. If you have an objective reason (or if you insist that your subjective feeling trumps mine), I'm OK with changing.

**Comment by frivoal** [comment]
@fantasai fixes based on the review are done. Ready for next round.

I've reworded the text instructions in -018 and -019, hopefully the problem you had with them are gone now.

I've been through the green square tests, and reworked quite a few of them.

I think the worst offender was by far the first one (-006), so I've made it into a much simpler test with a different reference.

For most of the other tests, It seemed to me that what made them hard to understand was not so much trying to make them match the standard green square, but the way I was doing it, applying a whole bunch of properties onto a single element, leaving the reviewer with quite a puzzle trying to figure out how it all fits together. I've rewritten them by separating out the various part (the thing that makes a green backdrop, the thing that may turn red on top of it if the test fails...), making it hopefully much clearer and easier to work with, still matching the green square. Hopefully you agree that it is not ok. If not, I'll need more detailed coaching about why it's not.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5285; please continue all discussion there.

**Pull request closed without merging**
