### PR TITLE
new text-transform tests

### PR DESCRIPTION
**Pull request by r12a**
For overview and results see http://www.w3.org/International/tests/repo/results/text-transform

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/763)

### CODE REVIEW

**Comment by r12a** [comment]
I think that spec links are not an issue.
I already removed some metadata. 
Do i really need to remove assertions?

**Comment by r12a** [comment]
it would be useful for the validation checker to report duplicate metadata

i think the tests are now good to go

**Comment by r12a** [comment]
it would be useful for the validation checker to report duplicate metadata

i think the tests are now good to go

**Comment by kojiishi** [comment]
* css-counter-styles-3/i18n/css3-counter-styles-016a.html is included. Is this by accident?
* Mind to change tabs to spaces, as per the [style guidelines](http://testthewebforward.org/docs/test-format-guidelines.html#style-rules)?
* Not quite sure "../../fonts" works, as the [test harness](http://test.csswg.org/harness/) moves all files to a single flat directory. See issue #766. If you think it should work, we could land this and fix only if it doesn't.

**Comment by kojiishi** [comment]
For "../../fonts" path issue, please refer to [a mail in public-css-testsuites from Peter](https://lists.w3.org/Archives/Public/public-css-testsuite/2015Jun/0022.html).

**Comment by r12a** [comment]
@kojiishi for ../../fonts path issue see https://github.com/w3c/csswg-test/pull/734#issuecomment-78388483
i'm trying to find a way to write tests that work equally well in the CSS test suite and in the i18n test suite, and anywhere else, and don't require me to change things before moving from one place to another

**Comment by kojiishi** [comment]
@r12a:
> for ../../fonts path issue see #734 (comment)

Peter said "relative *script* paths" so I wonder it does not support font URLs. If we would like to try it out, I'm happy to merge and see how it goes. Would you prefer that?

**Comment by plinss** [comment]
There's no support for fixing up relative paths to fonts at this time. Using "../../fonts" will not work in a built test suite.

You'll need to copy any needed fonts into a "support" subdirectory.

**Comment by r12a** [comment]
the tests i write for the i18n test suite follow the TTWF pattern closely, but there are some differences in where to find support files. 

The differences include the location of the javascript test files, which cannot be accessed from the root directory in the W3C site, and font files, which i don't want to scatter around my hard drive and the W3C server. There may also be links to alternative style sheets of a general nature (to produce, from the same result data, the more graphic-oriented test results pages we use).  

I can no longer find sufficient bandwidth to adapt the i18n tests as necessary to fit the CSS test suite, and then shepherd them through the process (though i will try to check for test errors and update the i18n tests accordingly).

I am also unable to justify the non-trivial amount of time needed to create additional ref files, since  they are not actually used afaict. (Of course each ref test has a reference div on the same page – i'm just talking about the separate pages required by the TTWF process.)

If someone is able/interested to make what changes are required and shepherd the tests through the process, they are welcome, and i'd be happy to notify them when new tests become available (eg. there are a set of new  vertical text and css ruby tests already) and where to find them.  The tests themselves are organized on the w3c server in directories that mirror those used in the CSS test suite.

(fwiw, the test in this pull request are still the same, as far as i'm aware, as those accessed from http://www.w3.org/International/tests/repo/results/text-transform)

if there is a volunteer to help with this, they can adapt the files as needed and send a new pull request. Otherwise, i suggest we just close this pull request.

**Comment by r12a** [comment]
> css-counter-styles-3/i18n/css3-counter-styles-016a.html is included. Is this by accident?

no, that file needs updating, so i included it in this PR rather than creating another

**Comment by kojiishi** [comment]
Merging, knowing there are some link/style issues. Please refer to #911 for more details.

**Pull request merged**
