### PR TITLE
[css-flexbox-1] Add a test for definite cross sizes

### PR DESCRIPTION
**Pull request by cbiesinger**
[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1057)

### CODE REVIEW

**Comment by dholbert** [comment]
This testcase doesn't seem to set `display:flex` on anything, so I think it might not be testing what you want it to test... Right now it has:
````
 .flexbox {
  width: 50px;
  outline: 3px solid black;
}
````
I expect you want to have `display:flex` in there?

Also, might be worth giving all of the flex items all `min-height:0`, so that there's no chance of spuriously "passing" a piece of the test simply because we're stopping a flex item from shrinking below its intrinsic minimum size.

**Comment by cbiesinger** [comment]
Oh that's a little subtle. The display: flex is set by the included stylesheet:
+<link rel="stylesheet" href="support/flexbox.css">

but the min-height is a good point. Will change.

**Comment by dholbert** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[css-flexbox-1/definite-cross-sizes.html, line 38 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIQ8v-XjhJ4_jhcnHC:-KCIQ8v-XjhJ4_jhcnHD:-1767485284) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/definite-cross-sizes.html#L38)):*
Nit: This sentence ("Tests that we ...") ends in a period, but all the ones after it do not.

Really, they might all want to end in a colon, since they're all referring to the content directly after them...?

Regardless, probably best to make these consistent.

---

*[css-flexbox-1/definite-cross-sizes.html, line 65 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIQTB63ZtqoLvw1u9z:-KCIQTB63ZtqoLvw1uA-:400756160) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/definite-cross-sizes.html#L65)):*
Nit: s/an definite/a definite/  (drop the "n" from "an")

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by dholbert** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[css-flexbox-1/definite-cross-sizes.html, line 1 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCISF3qOS5PXGXywzXW:-KCISF3qOS5PXGXywzXX:2111335429) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/definite-cross-sizes.html#L1)):*
This test's filename ("definite-cross-sizes") probably needs to include e.g. "001", right?  Really, it might want to be named percentage-heights-001.html, since it's about percentage heights, and it's using the same `check-layout-th.js` library that the existing percentage-heights-000.html testcase uses.

---

*[css-flexbox-1/definite-cross-sizes.html, line 5 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIS1p6WobdrRZsdFqb:-KCIS1p7rt0_aTK0vJw6:378597318) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/definite-cross-sizes.html#L5)):*
For consistency, I think this <style> block should come after all of the other boilerplate (the help/author tags in particular).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by dholbert** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[css-flexbox-1/definite-cross-sizes.html, line 5 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIS1p6WobdrRZsdFqb:-KCIT9ZDnjID0Ay69xQ_:1027067489) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/definite-cross-sizes.html#L5)):*
(er, I typed "this `<style>` block", but I forgot to include backticks, so reviewable ate the `<style>`.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by cbiesinger** [comment]
*[css-flexbox-1/percentage-heights-001.html, line 38 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIQ8v-XjhJ4_jhcnHC:-KgGRveHo6YjOi4rKIFn:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/percentage-heights-001.html#L38)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

Nit: This sentence ("Tests that we ...") ends in a period, but all the ones after it do not.

Really, they might all want to end in a colon, since they're all referring to the content directly after them...?

Regardless, probably best to make these consistent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by cbiesinger** [comment]
*[css-flexbox-1/percentage-heights-001.html, line 5 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIS1p6WobdrRZsdFqb:-KgGRqUv9KmzqxrRAje2:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/percentage-heights-001.html#L5)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

(er, I typed "this `<style>` block", but I forgot to include backticks, so reviewable ate the `<style>`.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by cbiesinger** [comment]
*[css-flexbox-1/percentage-heights-001.html, line 65 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCIQTB63ZtqoLvw1u9z:-KgGS0LXcJjhkAGfuMoG:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/percentage-heights-001.html#L65)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

Nit: s/an definite/a definite/  (drop the "n" from "an")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by cbiesinger** [comment]
*[css-flexbox-1/percentage-heights-001.html, line 1 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1057#-KCISF3qOS5PXGXywzXW:-KgGRrlt6INYi_OehYlI:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/9dbf389412cbc8299de96a1a59ea4723b226226a/css-flexbox-1/percentage-heights-001.html#L1)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

This test's filename ("definite-cross-sizes") probably needs to include e.g. "001", right?  Really, it might want to be named percentage-heights-001.html, since it's about percentage heights, and it's using the same `check-layout-th.js` library that the existing percentage-heights-000.html testcase uses.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1057)*

**Comment by cbiesinger** [comment]
All changes made, but please hold off while I verify this is all still correct.

**Comment by cbiesinger** [comment]
OK, this should be ready for merging -- updated to the current version of the spec (I think), and updated with a couple more tests from the current version of this testcase in blink.

r? @fantasai @dholbert

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5282; please continue all discussion there.

**Pull request closed without merging**
