### PR TITLE
Submit Ji Kai's transforms test.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1002)

### CODE REVIEW

**Comment by fantasai** [comment]
@gsnedders This is a trivial commit that fixes permissions on a file and changes the spec links. I think we should definitely take the permissions fix. Unsure about the spec link change, doesn't seem necessary. (Though publishing an update to Transforms is definitely necessary.)

**Comment by fantasai** [comment]
@gsnedders Since you're more familiar with which set of spec links we consider canonical, I'll let you make the call on that, but otherwise please merge this.

**Comment by gsnedders** [comment]
@fantasai and moves them out of `work-in-progress` (which is excluded from the built testsuites), hence the whole test actually needs reviewed

**Comment by fantasai** [comment]
Ah, fair enough. Um. I can't tell what the test is trying to test. :( The assert is talking about a scale, but there is no scale in the test.

**Comment by fantasai** [comment]
It's otherwise a good test. The main complaint I have is it's comparing the thing it wants to test (a rotate function) with an SVG with a 3-parameter rotate function, which doesn't seem to qualify as "simpler" functionality, really. I'm also concerned that we might hit anti-aliasing issues, but that's a problem any time we're testing non-orthogonal paint boundaries.

**Pull request merged**
