### PR TITLE
[css-ui-3] Add test for incremental text-overflow

### PR DESCRIPTION
**Pull request by notriddle**
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1176)

### CODE REVIEW

**Comment by notriddle** [comment]
The @syncbot issues should be resolved, now.

**Comment by notriddle** [comment]
I guess I need to use a `mailto` URL for the author annotation?

**Comment by notriddle** [comment]
What's wrong with the author syntax?

**Comment by notriddle** [comment]
link uses rel. The link tag uses rel, not name.

**Comment by notriddle** [comment]
Sorry about all that.

**Comment by frivoal** [comment]
Nothing to be sorry about, thanks for the submission. The linter / automated checker hasn't been fully updated yet, and is stricter than it needs to be (for example, author information should adequately be covered by commit metadata).

The test is good. There's a could of tweaks I'd like to do before merging, but they're not worth bothering you for, so I've made  #1177 based on this one

**Comment by frivoal** [comment]
Merged #1177, which includes this.

**Pull request merged**
