### PR TITLE
Florian/cursor tests

### PR DESCRIPTION
**Pull request by frivoal**
This add a bunch of tests for the cursor property.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/783)

### CODE REVIEW

**Comment by cvrebert** [comment]
Does the [`-manual` naming convention](http://testthewebforward.org/docs/manual-test.html#requirements-for-a-manual-test) not apply for some reason?

**Comment by frivoal** [comment]
That convention is not used as far as I know within the csswg tests. The documentation you're referring to is written to apply both to csswg tests and to https://github.com/w3c/web-platform-tests, and the author of this section might simply have missed out on this difference between the two groups.

It wouldn't be wrong to use this suffix in the csswg, but it isn't required either, and I wasn't aware of this convention until you pointed it out.

**Comment by frivoal** [comment]
Actually, the css naming convensions (as opposed to the web-platform-tests naming convensions) are documented here: http://testthewebforward.org/docs/css-naming.html

**Comment by cvrebert** [comment]
Ah, I see. The docs don't quite make that clear currently.

**Comment by frivoal** [comment]
@tantek or @svgeesus, could you review these tests, and merge them if everything's fine?

**Comment by frivoal** [comment]
@tantek ping

**Comment by frivoal** [comment]
@tantek @gsnedders @bert-github @svgeesus Anyone up for reviewing these tests? Thanks.

**Comment by bert-github** [comment]
On Sunday, December 4, 2016 9:57:49 PM CET Florian Rivoal wrote:
> @tantek @gsnedders @bert-github @svgeesus Anyone up for reviewing these
> tests? Thanks.

I see 39 short files and, at first sight, they look pretty 
straightforward. Many also seem similar... Yes, I should be able to 
review them later this week.



Bert
-- 
  Bert Bos                                ( W 3 C ) http://www.w3.org/
  http://www.w3.org/people/bos                               W3C/ERCIM
  bert@w3.org                             2004 Rt des Lucioles / BP 93
  +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France

**Comment by gsnedders** [comment]
@frivoal @cvrebert I expect at least post-wpt merge there's going to be a blanket requirement that we use `-manual` and `-visual`, FWIW.

**Comment by frivoal** [comment]
@gsnedders Currently that's handled through flags. I personnally don't care how it's signaled as long as it's signaled some way. If we need to switch from flags to naming conventions, why not, and I am not sure we even need to wait. Do you want to start a separate discussion about that?

**Comment by bert-github** [comment]
About css-ui-3/cursor-020.html

The specification doesn't actually say that UAs must use the 'pointer' value on links, does it?

About: css-ui-3/cursor-auto-005.html

The spec says: "User agents **may** [my emphasis] ignore the cursor property over native user-agent controls". So I think the flags need the "may" keyword.

Otherwise all the tests seem correct.

**Comment by frivoal** [comment]
> About css-ui-3/cursor-020.html

> The specification doesn't actually say that UAs must use the 'pointer' value on links, does it?

You're right. This is expected to come from UA stylesheets (rather than from some `auto` magic), but the spec doesn't say so. We should probably bring that up to the WG, but for the test, I've changed the text to "The test passes if, when moved inside the blue box, the cursor indicates a link. Often rendered as the backside of a hand with the index finger poiting and the other fingers closed.". Is that ok?

>About: css-ui-3/cursor-auto-005.html

> The spec says: "User agents may [my emphasis] ignore the cursor property over native user-agent controls". So I think the flags need the "may" keyword.

Agreed. I've fixed the test.

**Comment by frivoal** [comment]
Thanks!

**Pull request merged**
