### PR TITLE
Add test of sanity of collapsing borders when there's an empty <tbody>

### PR DESCRIPTION
**Pull request by cvrebert**
Refs http://bugzil.la/1023761 & https://github.com/twbs/bootstrap/issues/13453

### CODE REVIEW

**Comment by cvrebert** [comment]
@frivoal Sorry to bother you, but since you were so helpful previously, I wonder if you could advise me on how/who I should ping to get this reviewed?

**Comment by frivoal** [comment]
CCing a few people who might know something: @bert-github @fantasai @tabatkins 

@cvrebert sorry for the slow answer, I was traveling. Your test looks sane to me, but I am not a table expert, so I'd rather have someone else review it.

Things related to tables are tricky, since they do not really have an active maintainer, but let's see if any of the CCed people can help.

**Comment by dbaron** [comment]
The test seems reasonable to me; the only oddity seems to be that it's also implicitly testing the differences between default styles of td and th.

I guess https://bugzilla.mozilla.org/show_bug.cgi?id=1023761 covers the Gecko bug here.

**Comment by cvrebert** [comment]
Thank you! :beers:

**Pull request merged**
