### PR TITLE
Add first visibility:collapse test

### PR DESCRIPTION
**Pull request by davidsgrogan**
visibility:collapse test that shows effects of a collapsed row on table height and width

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1213)

### CODE REVIEW

**Comment by gregwhitworth** [comment]
@gsnedders Hey do you have any idea as to why this is failing? Should we care?

**Comment by davidsgrogan** [comment]
ping @gsnedders

**Comment by gsnedders** [comment]
I have literally never seen anything like this. Travis is certainly doing something weird. :\

@davidsgrogan Is there any reason why this branch is based on a commit on `master` from June 2016? That might not be helping matters given all the changes to the Travis setup since. Could you try merging/rebasing and then pushing that and see if it makes Travis happy?

**Comment by davidsgrogan** [comment]
If I merge `master` and push the result then all of `master`'s commits since June 2016 will show up here (right?), which I don't think I want. @gregwhitworth or @FremyCompany, want to weigh in here? Are you up for merging `master` with `css-tables`?

And, sorry, I know Greg told me but I forgot why the `css-tables` branch was created originally. If it's no longer an issue, should I just submit a PR against `csswg-test:master`?

**Comment by gregwhitworth** [comment]
Yeah we added it because technically this spec isn't solid so we wanted a branch where these things lived without messing with master, so if someone got irritated that we were adding folders where we shouldn't be it would be in a branch where no one cared. At any rate if we merge now we should only end up with your one file, not all of the differences between then and now as seen in "This branch has no conflicts". I just don't know what Travis is trying to do and didn't want to break something. @davidsgrogan Do you mind if I just grab your file, and add it via my repo? Then you can do a new clean fork and we should be good?

**Comment by davidsgrogan** [comment]
Doesn't "This branch has no conflicts" mean that w3c/csswg-test:css-tables and davidsgrogan/csswg-test:css-tables don't conflict? I don't think it's referring to any fork's `master` branch.

At any rate, grabbing the file sounds good. I also submitted https://github.com/w3c/csswg-test/pull/1215

**Comment by gsnedders** [comment]
Oh wait you're merging into css-tables. I'm blind. :)

**Comment by gsnedders** [comment]
@gregwhitworth @FremyCompany can we merge master into css-tables without issue?

**Comment by gregwhitworth** [comment]
Alrighty, as stated in #1215 I've rebased with master and manually verified that this causes no issues in the tables branch. I've merged it in. Thanks for the test @davidsgrogan

**Comment by davidsgrogan** [comment]
Thanks for sticking with it.

**Pull request merged**
