### PR TITLE
remove unnecessary style declaration from tcu reference file

### PR DESCRIPTION
**Pull request by myakura**
see: http://lists.w3.org/Archives/Public/public-css-testsuite/2014Nov/0014.html

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/657)

### CODE REVIEW

**Comment by kojiishi** [comment]
@myakura I can take a look, but it looks like there's a merge conflict. Can you fix?

**Comment by myakura** [comment]
looks like I messed up w/ my remote branch as GitHub doesn't update the PR (instead closing it :(

**Comment by kojiishi** [comment]
@myakura looks like you're removing several files in css-ui-3, merge failure?

**Comment by kojiishi** [comment]
Picked only correct commit manually.

**Pull request closed without merging**
