### PR TITLE
[css-text-3] White space pre wrap end of line

### PR DESCRIPTION
**Pull request by frivoal**
Adding some tests to check preserved spaces at the end of the line when the white-space property is pre-wrap.

Checking that the property which is supposed to influence that properly does (overflow-wrap), as well as checking that those that shouldn't don't (since in some browsers, they currently do).

Also including the same tests based on a regular div and on a textarea, since by spec there should be no difference, but in some implementations there is.

---

This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1137)

### CODE REVIEW

**Comment by frivoal** [comment]
@kojiishi @fantasai Can i haz review? thxbye.

**Comment by frivoal** [comment]
@kojiishi @fantasai @gsnedders I'd appreciate a review of the tests, thanks.

**Comment by frivoal** [comment]
@kojiishi @fantasai A review of these tests would be very much appreciated, to land them before the switch to the wpt repo.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5283; please continue all discussion there.

**Pull request closed without merging**
