### PR TITLE
[css-grid] Fix 100x100-green.png support image

### PR DESCRIPTION
**Pull request by mrego**
The image was not using exactly the expected green,
so the test was failing when it was run automatically
(see http://crbug.com/692754).

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1202)

### CODE REVIEW

**Comment by javifernandez** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1202#-:-Kd2yiQFZBJAQDpDhJKv:bnfp4nl)*

**Comment by javifernandez** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1202)*

**Comment by mrego** [comment]
I'm not sure this will be right or enough, as I've seen issues with other green images in different platforms.
For example [this issue in Mac](https://storage.googleapis.com/chromium-layout-test-archives/mac_chromium_rel_ng/389242/layout-test-results/external/csswg-test/css-grid-1/grid-items/grid-minimum-size-grid-items-006-diffs.html).

So I need to investigate this properly (dunno if it's related to the retina displays, hdpi or what) and try to generate good *green* images if possible.

**Comment by mrego** [comment]
Thanks to @Ms2ger suggestion I've found a good solution for this.
I'll use the images on the reference file, so we're actually comparing images against images, not images against CSS colors.
I'll do that on PR #1204, so closing this.

**Pull request closed without merging**
