### PR TITLE
[css-flexbox] Add tests for intrinsic sizing behavior

### PR DESCRIPTION
**Pull request by cbiesinger**
[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1022)

### CODE REVIEW

**Comment by cbiesinger** [comment]
@tabatkins @fantasai  - can one of you review this?

**Comment by dholbert** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[css-flexbox-1/intrinsic-height-000-ref.html, line 3 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1022#-KCIApSekZ2bJ7p5pzK4:-KCIApSekZ2bJ7p5pzK5:60745725) ([raw file](https://github.com/w3c/csswg-test/blob/a6416d9d0cbe3b6863e899bcd2e69607dd42b0eb/css-flexbox-1/intrinsic-height-000-ref.html#L3)):*
This title is probably too vague; it doesn't really say what the test is testing.

I think you mean to say, "Test that flex container's intrinsic size is influenced by its items' flex-grow values" or something like that?

---

*[css-flexbox-1/intrinsic-height-000-ref.html, line 30 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1022#-KCIAjkJTtTxuOhvbLI4:-KCIAjkK2Asxn_O6YtLr:2082732682) ([raw file](https://github.com/w3c/csswg-test/blob/a6416d9d0cbe3b6863e899bcd2e69607dd42b0eb/css-flexbox-1/intrinsic-height-000-ref.html#L30)):*
The phrase "next to" is wrong here, for the height-000 testcase & its reference (which use vertical flex containers whose items are stacked vertically).

I think you mean to say "above" instead of "next to".

---

*[css-flexbox-1/intrinsic-width-000.html, line 18 \[r1\]](https://reviewable.io:443/reviews/w3c/csswg-test/1022#-KCIC7tIQbW8Wm43USzE:-KCIC7tJMVOBn--Kl17e:-215950182) ([raw file](https://github.com/w3c/csswg-test/blob/a6416d9d0cbe3b6863e899bcd2e69607dd42b0eb/css-flexbox-1/intrinsic-width-000.html#L18)):*
It seems here you're assuming that a flex item with "width: 200px; flex: 1 1 0" has a max-content contribution of 200px.  I don't think that's correct. The spec defines flex items' min-content and max-content contributions as being determined by their intrinsic sizes, flex-basis, and min/max-width|height properties, here: https://drafts.csswg.org/css-flexbox-1/#intrinsic-item-contributions .  I don't think that spec-text has any way for "width" or "height" to influence the item's max-content contribution, in your example here (with flex-basis:0)...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/w3c/csswg-test/1022)*

**Comment by cbiesinger** [comment]
All comments fixed, please take a look! @fantasai @dholbert

**Comment by cbiesinger** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[css-flexbox-1/intrinsic-height-000-ref.html, line 3 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1022#-KCIApSekZ2bJ7p5pzK4:-KgGhTDFAmZcBGkRa2VZ:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/a6416d9d0cbe3b6863e899bcd2e69607dd42b0eb/css-flexbox-1/intrinsic-height-000-ref.html#L3)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

This title is probably too vague; it doesn't really say what the test is testing.

I think you mean to say, "Test that flex container's intrinsic size is influenced by its items' flex-grow values" or something like that?
</blockquote></details>

Done.

---

*[css-flexbox-1/intrinsic-height-000-ref.html, line 30 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1022#-KCIAjkJTtTxuOhvbLI4:-KgGhTzkjosJSmOkZ-ek:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/a6416d9d0cbe3b6863e899bcd2e69607dd42b0eb/css-flexbox-1/intrinsic-height-000-ref.html#L30)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

The phrase "next to" is wrong here, for the height-000 testcase & its reference (which use vertical flex containers whose items are stacked vertically).

I think you mean to say "above" instead of "next to".
</blockquote></details>

Done.

---

*[css-flexbox-1/intrinsic-width-000.html, line 18 at r1](https://reviewable.io:443/reviews/w3c/csswg-test/1022#-KCIC7tIQbW8Wm43USzE:-KgGhUiQ1JY6yVNgLaDG:b-896fix) ([raw file](https://github.com/w3c/csswg-test/blob/a6416d9d0cbe3b6863e899bcd2e69607dd42b0eb/css-flexbox-1/intrinsic-width-000.html#L18)):*
<details><summary><i>Previously, dholbert (Daniel Holbert) wrote…</i></summary><blockquote>

It seems here you're assuming that a flex item with "width: 200px; flex: 1 1 0" has a max-content contribution of 200px.  I don't think that's correct. The spec defines flex items' min-content and max-content contributions as being determined by their intrinsic sizes, flex-basis, and min/max-width|height properties, here: https://drafts.csswg.org/css-flexbox-1/#intrinsic-item-contributions .  I don't think that spec-text has any way for "width" or "height" to influence the item's max-content contribution, in your example here (with flex-basis:0)...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/csswg-test/1022)*

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5281; please continue all discussion there.

**Pull request closed without merging**
