### PR TITLE
Remove links to non-existent reference files in css-text-3/i18n.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/911)

### CODE REVIEW

**Comment by kojiishi** [comment]
I think some (most/all?) of them are to be fixed in #763 but it's not landed for a while due to some issues remaining in the tests. I wonder it's better to land it anyway before removing reference links...

**Comment by Ms2ger** [comment]
Since that PR doesn't seem to be going anywhere, I'd prefer to land this.

**Comment by plinss** [comment]
Rather than remove links to non-existent reference files, maybe provide the reference file instead? Either re-create it or get the original test author to cough it up.

**Comment by kojiishi** [comment]
#763 has issues but also has some good staff too. @r12a doesn't seem to be able to fix them, what about:

1. Land it anyway. The spec is still at LC (and has been so quite a long time,) I hope unstabilizing it for a while doesn't harm anyone.
2. See how much it breaks and fix as appropriate, including adding missing ref files if there were any.
3. If any tests don't look worth spending time to fix (or re-create ref files) we can remove either the tests or ref links.

I think @r12a is happy to provide the original test/ref files if anyone here is happy to try to adopt to CSS WG styles.

**Comment by Ms2ger** [comment]
@gsnedders fyi

**Comment by gsnedders** [comment]
I'd much rather not have warnings lying around with no real plan to fix them. Having missing refs links gains us nothing (because it's practically equivalent to purely visual tests), and makes it harder to run the tests (as if you parse out the list of tests from testinfo.data you'll get references that don't exist).

**Comment by kojiishi** [comment]
Yeah, so the real plan is  land #763 and fix as needed, if no objections. Does that sound OK?

**Comment by kojiishi** [comment]
20 days without strong objections indicates no strong objections, so I'm taking #763 and see how to fix that. I understand some people do not prefer possible unstabilizations, but I hope it's for short period, and is worth to take the tests from r12a.

I'm not aware of anyone running these tests regularly, apologies if anyone does so today and the merge troubles. Please let this thread or #763 know if so and I'll try to make the impact minimal.

**Comment by kojiishi** [comment]
Ah, ok, so by merging I noticed @r12a submitted 2 different sets of tests:
* css-text-3/i18n/css3-text-text-transform-*
* css-text-3/text-transform/text-transform-*

and this PR is about the former while #763 is about the latter.

@r12a, could you confirm whether these tests are duplicate and we can completely remove the former, or they're actually different tests?

**Comment by kojiishi** [comment]
After talking to @r12a, the new tests in #763 (css-text-3/text-transform) are newer and superset of css-text-3/i18n/css3-text-text-transform-*, so he said removing them is fine.

I have removed them, and thus this PR is no longer necessary. Sorry for the trouble.

**Pull request closed without merging**
