### PR TITLE
[cssom-view-1] Fix outdated/broken spec anchors

### PR DESCRIPTION
**Pull request by cvrebert**
```
Test links to unknown specification anchor: http://www.w3.org/TR/cssom-view/#widl-Document-elementFromPoint-Element-float-x-float-y
  in: cssom-view-1/elementFromPosition.html
Test links to unknown specification anchor: http://www.w3.org/TR/cssom-view/#the-getclientrects-and-getboundingclientrect-methods
  in: cssom-view-1/ttwf-js-cssomview-getclientrects-length.html
```

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1026)

### CODE REVIEW

**Comment by cvrebert** [comment]
@plinss Is something wrong with the validator here? The revised spec links seem fine to me...

**Comment by gsnedders** [comment]
@cvrebert the canonical links are still HTTP, hence it doesn't work :\

**Comment by plinss** [comment]
I updated Shepherd (the validator) to accept either http or https links for specs, so you should be good to go now.

**Comment by cvrebert** [comment]
Wünderbar. Thanks!

**Pull request merged**
