### PR TITLE
Test for caret-color

### PR DESCRIPTION
**Pull request by frivoal**
The first 3 are updates to previous tests from Chris because the spec changed after he wrote them, and based on reviews here:
http://test.csswg.org/shepherd/testcase/caret-color-001/spec/css-ui-3/
http://test.csswg.org/shepherd/testcase/caret-color-002/spec/css-ui-3/
http://test.csswg.org/shepherd/testcase/caret-color-003/spec/css-ui-3/

The rest are new tests.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/916)

### CODE REVIEW

**Comment by frivoal** [comment]
@tantek Can you have a look at this, and hopefully merge if everything looks good?

**Comment by frivoal** [comment]
@tantek ping

**Comment by plinss** [comment]
Please don't create PR branches in the main repo, use a private repo as the source of the PR.

**Comment by frivoal** [comment]
@plinss I'm pretty sure that's what I did.

> syncbot merged 8 commits into w3c:master from frivoal:florian/caret-color-tests 2 days ago 

what makes you think I got it wrong?

**Comment by frivoal** [comment]
@gsnedders Why does syncbot merge things? Especially things that haven't been reviewed yet. I would expect merging to only happen after review has happened.

(This is my stuff, so I am happy to have it merged, but I'd rather have that for the right reasons).

**Comment by gsnedders** [comment]
@frivoal ask @plinss that :)

**Comment by frivoal** [comment]
@gsnedders I thought you knew everything about tests :)

@plinss, see [above](https://github.com/w3c/csswg-test/pull/916#issuecomment-223849162).

**Comment by frivoal** [comment]
@plinss, @gsnedders , I did make the PR from my personal repo, but it does look like I also accidentally pushed that branch to the main repo at some point. My bad.

Should we somehow unmerge this until it is reviewed? Is the `stale:awaiting-review` tag sufficient? Should we instead open an issue about reviewing these already merged tests?

I don't really care strongly one way or another, and you two are the guardians of the test process (or something like that), so you tell me. I just want to get these reviewed at some point, so I don't want to lose track of the fact that they haven't been yet.

**Pull request merged**
