### PR TITLE
Update links.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1063)

### CODE REVIEW

**Comment by zcorpan** [comment]
The old and new URL point to the same document, AFAICT. New work is at https://drafts.csswg.org/css2/ but I'm not sure that will pass the lint check...

**Comment by Ms2ger** [comment]
Don't know about the draft url either; this change gets the tests added to the compiled suite, at least.

**Comment by plinss** [comment]
The new URL (w3.org/TR/CSS21) is the correct url to use for the test build system (which is also what let's it pass the linter). The draft URL https://drafts.csswg.org/css2/ also works.

**Comment by Ms2ger** [comment]
@plinss in that case, merge please? :)

**Pull request merged**
