### PR TITLE
Add test that transitionend is not fired after element is made display:none

### PR DESCRIPTION
**Pull request by cvrebert**
See also http://crbug.com/437860, http://bugzil.la/1182856

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @dbaron (as an Editor of the relevant specs)

**Comment by cvrebert** [comment]
CC: @tabatkins (as the one who [proposed the relevant behavior clarification](https://lists.w3.org/Archives/Public/www-style/2015Apr/0405.html))

**Comment by dbaron** [comment]
Is this two copies of the same test?  If so, why?  Seems better to just have one copy, tagged for level 1 of transitions (i.e., css3-transitions).

**Comment by cvrebert** [comment]
@dbaron I wasn't sure which level the spec clarification applied to. I've now removed the `css-transitions-2` copy.

**Comment by dbaron** [comment]
Did you test the test locally to see that it behaves as you expect?

I'm a little confused since part of the test uses a variable called "div" and part uses a variable called "e", which looks like it's meant to be the same thing.  I'd think that running the JS would throw an exception when trying to access e.className when e is undefined, although maybe I'm missing something.

**Comment by cvrebert** [comment]
@dbaron No, you're right. This is what I get for trying to rename a variable late in the game. Fixed that and re-tested locally; it works.
Convenient live copy of the test: http://jsbin.com/hivira/edit?html,output

**Comment by cvrebert** [comment]
Thank you

**Pull request merged**
