### PR TITLE
Reduce the number of copies of ref-filled-green-100px-square.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1037)

### CODE REVIEW

**Comment by frivoal** [comment]
@plinss I'm tempted to approve and merge this, as it seems very sensible to me, but is there a tooling related reason for keeping duplicates around?

**Comment by plinss** [comment]
The reason the support files are duplicated is because the build doesn't fixup any relative URLs to support files (yet), so they need to be in a 'support/' directory in the same directory as the test/reference. Files can be copied where needed throughout the repo and the build only takes one copy (giving a 'merge mismatch' error if the copies don't match).

**Comment by frivoal** [comment]
@plinss in this case, it is the reference of a ref-test, rather than support files, but I suppose the same logic applies? This would mean that the first commit in this pull request is fine, but the rest should wait for the build system to gain support for relative paths, right?

**Comment by plinss** [comment]
Ah, sorry, didn't see this was dealing with reference files. No, the build _does_ deal with reference file paths and fixes them up just fine, so while it's legal to do, there's no reason to have duplicate reference files in the repo. You can simply have a single copy of a reference file anywhere in the repo, and then just use the appropriate relative path to it from any test ("../../../../../reference/<filename>" is just fine). The only restriction is that the relative path must remain in the repo, and must be valid.

**Pull request merged**
