### PR TITLE
Change line endings (CRLF->LF) in all files with CR at EOL.

### PR DESCRIPTION
**Pull request by qyearsley**
Reason: Most files in this repo have Unix-style line endings, so using Unix-style line endings seems better for consistency.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1157)

### CODE REVIEW

**Comment by gsnedders** [comment]
@qyearsley I'm not quite sure what you've done here, but something wrong, seemingly adding CRs! `lint.whitelist` should probably change as well.

**Comment by gsnedders** [comment]
Have those with Unix line endings gone to Windows line endings and those with Windows line endings gone to Unix?

**Comment by qyearsley** [comment]
Yeah, something seems to have gone wrong with this PR, and changing lint.whitelist looks like it could prevent this in the future :-) I'll close this PR and try to make another one

**Comment by gsnedders** [comment]
@qyearsley You can just force-push to the same branch; there's no actual need to create a new PR.

**Comment by qyearsley** [comment]
Thanks @gsnedders :-D Just tried fixing the patch and pushing again, and expanded the scope of the change to include all files with CRLF endings -- although some of these files have a separate issue -- "Not linked to a tracked specification anchor." -- so this couldn't be merged as-is, right?

**Comment by plinss** [comment]
The spec anchor issues are due to the spec DB not having the /TR version listed. I fixed that in the DB so those issues can be ignored.

**Comment by qyearsley** [comment]
Ah, thanks :-)

I'm unsure what to do next -- https://travis-ci.org/w3c/csswg-test/builds/185939854 says that lint failed with "TRAILING WHITESPACE: css-fonts-3/test-synthetic-italic.xht 13 Whitespace at EOL", although css-fonts-3/test-synthetic-italic.xht isn't modified by this PR, I think

**Comment by gsnedders** [comment]
@jgraham @Ms2ger @sideshowbarker thoughts on the churn this causes? is it worth fixing? (I mean, we landed a bunch of whitespace fixes before, but we've mostly been all, "um, uh, um, uh", about fixing them globally.)

**Comment by gsnedders** [comment]
@qyearsley That's because master is failing, probably because someone pushed to directly either to hg or master here without running the lint first. :( If you throw up a second commit that fixes it that would be great!

**Comment by mrego** [comment]
> @qyearsley That's because master is failing, probably because someone pushed to directly either to hg or master here without running the lint first. :( If you throw up a second commit that fixes it that would be great!

I've fixed the trailing whitespace in #1164.

**Comment by qyearsley** [comment]
Thanks @mrego :-)

**Comment by plinss** [comment]
So it turns out the remaining spec link errors are actually real, the anchors in question moved from the round display spec to motion path (and the anchor names changes as well, so it's not a simple URL swap). Sorry I didn't catch that earlier.

**Pull request merged**
