### PR TITLE
[css-page] Fix 'page-container-009': Add page margins

### PR DESCRIPTION
**Pull request by kwkbtr**
The description in the test states that there is a margin around the edge of the page.
Added a page margin so that the description is valid even for user agents which have zero page margin in their default UA stylesheets.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/776)

### CODE REVIEW

**Comment by gsnedders** [comment]
I don't see the point of the second commit: it only changes whitespace, and given whitespace is collapsed by default (i.e., `white-space: normal`), there is no difference to the rendering.

The first commit looks good to me, though.

**Comment by kwkbtr** [comment]
> I don't see the point of the second commit: it only changes whitespace, and given whitespace is collapsed by default (i.e., `white-space: normal`), there is no difference to the rendering.

I think you are right in principle, but I had to make the change to avoid an error on automatic reftest with Google Chrome.
The original paragraph contains a double space after the first period (`page.  The top ...`).
Though such spaces should not cause any difference to the rendering (with `white-space: normal`) in theory, subpixel rendering of Google Chrome gives a different result and makes the reftest fail.

Rendering with the double space:
before

Rendering with a single space:
after

Difference (ignore differences in tab title and address bar):
diff

**Comment by RByers** [comment]
Weird.  There's a ton of complexity in text rendering (especially around sub-pixel support) that I know nothing about.  I'd suggest [filing a bug](https://crbug.com/wizard) indicating this is broken only in Chrome and I can make sure the right people take a look.

**Comment by fantasai** [comment]
@gsnedders The margin fix here should definitely be merged, even if the rewrapped prose isn't. I don't know what the procedure is for doing that, though.

**Comment by gsnedders** [comment]
Landed the first as eceee565be7ba74cc096abdf6bb7aa9514cecfc1.

**Pull request closed without merging**
