### PR TITLE
Add tests for get[Bounding]ClientRect[s] on Elements that aren't in the DOM

### PR DESCRIPTION
**Pull request by cvrebert**
Refs https://connect.microsoft.com/IE/feedback/details/829392/calling-getboundingclientrect-on-an-html-element-that-has-not-been-added-to-the-dom-causes-unspecified-error

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @zcorpan (since you're an Editor of the relevant module)

**Comment by cvrebert** [comment]
CC: @skynavga (as the other Editor of CSSOM View)

**Comment by tabatkins** [comment]
Look good, thanks!

**Comment by cvrebert** [comment]
Thank you for reviewing

**Pull request merged**
