### PR TITLE
Tests for focus :focus-within

### PR DESCRIPTION
**Pull request by frivoal**
This Pull Request builds on and replace https://github.com/w3c/csswg-test/pull/881, adjusting the tests based on comments in that pull request and on this mail thread: https://lists.w3.org/Archives/Public/public-css-testsuite/2015Sep/0019.html, and making a few other improvements.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/914)

### CODE REVIEW

**Comment by frivoal** [comment]
Is the Travis failure above something specific to these tests, or some problem with the travis checks themselves? I don't quite understand the error message, but it doesn't seem related to the tests.

**Comment by gsnedders** [comment]
@jgraham, @ms2ger: ^^

**Comment by Ms2ger** [comment]
Rebase the branch, please. That should fix it.

**Comment by frivoal** [comment]
I've merged master into this feature branch rather than rebase it. That should get it in sync with the latest things just as well, without messing with history and the branch tree.

**Comment by frivoal** [comment]
Doesn't seem to be helping. Or is there something special about rebasing that would fix it which merging master would not?

**Comment by Ms2ger** [comment]
Travis builds every commit in the PR branch in sequence. That means that any commit that's not a descendant of 833340c46a3f8edbd147674112e24051c459fb10 will break it.

**Comment by frivoal** [comment]
Alright, rebasing then. But why build every commit, rather than just the tip of the branch?

**Comment by frivoal** [comment]
@fantasai @tabatkins Everything lights up green now, can you review?

**Comment by cvrebert** [comment]
There seem to be several "focussed" [sic] typos.

**Comment by frivoal** [comment]
Oops. Thanks. Fixed the typos.

**Comment by frivoal** [comment]
@fantasai @tabatkins ping

**Comment by frivoal** [comment]
Thanks!

**Pull request merged**
