### PR TITLE
This is the monumental change to get rid of CRLF

### PR DESCRIPTION
**Pull request by gsnedders**
Yay consistent line-endings!

I recommend reading the commit message of the second commit in full—per prior agreement, that's the only one that needs reviewed.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/936)

### CODE REVIEW

**Comment by gsnedders** [comment]
Note that none of these are new breakages from these commits. They merely happen to be touched by this.

**Comment by Ms2ger** [comment]
Wasn't going to look at it, per se, but feel free to rebase/merge.

**Comment by kojiishi** [comment]
Sorry for not taking a look earlier, it looks like it conflicts. I'll try to look at quickly if you could rebase.

**Comment by kojiishi** [comment]
Alternatively, if you could list file names you examined safe to run dos2unix against, I can run and land manually. That should avoid conflicts best.

I ran though css-writing-modes-3 before, but neglected to go through all other directories.

**Comment by gsnedders** [comment]
I'll just rerun it soon and land it instantly, FWIW.

**Comment by kojiishi** [comment]
Thanks, wasn't sure you can land by yourself, lgtm.

**Pull request closed without merging**
