### PR TITLE
Set font when testing font relative units to make sure test is portable.

### PR DESCRIPTION
**Pull request by bemjb**
... is portable.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/687)

### CODE REVIEW

**Comment by gsnedders** [comment]
I find no evidence of this having been merged despite @rhauck's prior comment.

**Comment by svgeesus** [comment]
"merge pull request" is greyed out, because there is a travis integration test that seems to have timed out (like, last year). How to bump this forward?

**Review by svgeesus — APPROVED** [review]

**Comment by gsnedders** [comment]
@svgeesus well, given we've merged into web-platform-tests, this needs to be rebased/merged for that, and a PR opened there, which per what I've said before and the README on the homepage of the repo here, I'll do later this week

**Comment by csswg-test-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5252; please continue all discussion there.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5252; please continue all discussion there.

**Pull request closed without merging**
