### PR TITLE
Add OWNERS files.

### PR DESCRIPTION
**Pull request by tobie**
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1190)

### CODE REVIEW

**Comment by tobie** [comment]
@gsnedders LMK, if there are folks you want remove from all files (e.g. I remove @rhauck, as afaik she's working on completely different stuff these days).

**Comment by rhauck** [comment]
Yup. I'm not in these repos anymore.  Thanks @tobie!  Hope you're well.

**Comment by gsnedders** [comment]
@tobie Thanks! Don't worry about iterating from here, I can do that.

**Comment by gsnedders** [comment]
@Ms2ger do you want dropped rather than being in most of them?

**Comment by gsnedders** [comment]
I've added all editors to the OWNERS files (because, y'know, they should be interested in their specs being implemented interoperably!). There's a few editors who seem not to have GitHub accounts (should we be moving them to former editors?); notably, multi-col level 1 is edited by Håkon Wium Lie solely so *no* editor of that spec has a GitHub account! So, uh, sue me.

**Comment by frivoal** [comment]
@gsnedders 

> multi-col level 1 is edited by Håkon Wium Lie solely so no editor of that spec has a GitHub account

I have not yet had the chance to work do anything on that spec, but we have a resolution from way back adding me as a co-editor so that someone would deal with whatever needs to be dealt with. Feel free to add to that spec's OWNERS file

**Comment by gsnedders** [comment]
@frivoal You have access to the repo, feel free to add yourself wherever!

**Comment by Ms2ger** [comment]
Go ahead and drop me, please.

**Comment by gsnedders** [comment]
People who are in OWNERS files somewhere in the repo:

@astearns @atanassov @ayg @bemjb @bert-github @birtles @bradkemper @cabanier @cbiesinger @chenxix @chunywang @cvrebert @danielweck @dauwhe @dbaron @dirkschulze @fantasai @FremyCompany @frivoal @gregwhitworth @grorg @hakatashi @hober @hshiozawa @jgraham @JianfengXu @jihyerish @jxs @khaledhosny @kojiishi @kwkbtr @lilles @litherum @minxhuang @mrego @myakura @nattokirai @nikosandronikos @notriddle @nox @peterjoel @plinss @r12a @rniwa @rsheeter @rune-opera @sideshowbarker @SimonSapin @snsk @svgeesus @tabatkins @tantek @therealglazou @tomalec @tschneidereit @upsuper @web-flow @yunxiaoxie @zcorpan @zhorvath

These will only come into usage once the web-platform-test move happens; to quote the docs:

> OWNERS files are used only to indicate who should be notified of pull requests. If you are interested in receiving notifications of proposed changes to tests in a given directory, feel free to add yourself to the OWNERS file. Anyone with expertise in the specification under test can approve a pull request. In particular, if a test change has already been adequately reviewed "upstream" in another repository, it can be pushed here without any further review by supplying a link to the upstream review.

That said, we'd all *definitely* like people to take more interest in the test suites, especially for specs they're either editing or implementing. As I said in the above comment, editor's absolutely should have an interest in their test suites given they should be invested in both getting their specs to REC and in them being a success.

**Comment by gsnedders** [comment]
cc/ @tabatkins @tantek @therealglazou @tomalec @tschneidereit @upsuper @web-flow @yunxiaoxie @zcorpan @zhorvath given GitHub seems not to have linked you in the previous comment.

**Comment by gsnedders** [comment]
Anyone who doesn't want to be included who has push access should go ahead and remove themselves; anyone else comment here. We're not going for perfection for with the lists here, just a good starting point to iterate from.

**Comment by notriddle** [comment]
I'd like to be removed from the AUTHORS files.

**Comment by gsnedders** [comment]
Final call.

**Pull request merged**
