### PR TITLE
r12a/text align

### PR DESCRIPTION
**Pull request by r12a**
New tests for css-text-3 text-align and text-justify properties.

### CODE REVIEW

**Comment by r12a** [comment]
Hmm. I just spent a deal of time removing the author meta information from the ref files because the documentation says "The reference file must look exactly like the test file, except that the code behind it is different. -  All metadata is removed."

Do i have to go back through and change them all again?

And could someone please update the documentation so that others don't have this problem? http://testthewebforward.org/docs/reftests.html

**Comment by plinss** [comment]
On Mar 10, 2015, at 1:00 AM, r12a <notifications@github.com> wrote:

> Hmm. I just spent a deal of time removing the author meta information from the ref files because the documentation says "The reference file must look exactly like the test file, except that the code behind it is different. - All metadata is removed."
> 
Ugh. I don't know why that's stated in the documentation, there's no point in removing metadata from a reference. Having author/reviewer information is valuable for every file.

Reference files (that are not tests in and of themselves) must NOT have specification links, and must NOT have assertions, any other metadata is fair game.

> Do i have to go back through and change them all again?
> 
You don't _have_ to  in the sense that we're not going to reject your tests because they're missing author metadata, but if it's not a big deal, we wouldn't mind...

> And could someone please update the documentation so that others don't have this problem? http://testthewebforward.org/docs/reftests.html
> 

Will do.

Peter

**Comment by r12a** [comment]
ok, i added back the author information for the ref files. Hopefully, the tests are ok now.
ri

**Comment by r12a** [comment]
For results of these tests on major browsers see http://www.w3.org/International/tests/repo/results/text-align

**Pull request merged**
