### PR TITLE
Update LICENSE so it's not just a pointer to another document

### PR DESCRIPTION
**Pull request by cvrebert**
I've been told that the `LICENSE` file should contain actual copyright & license text before I can send additional PRs, hence this PR that copies in the relevant legalese from the webpages.

I'm not sure how to route this for review, so my apologies in advance, but CCing @svgeesus @sideshowbarker in hopes that they can help.

---

This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1091)

### CODE REVIEW

**Comment by frivoal** [comment]
CC @astearns @atanassov

**Comment by cvrebert** [comment]
@astearns @svgeesus Any chance of getting the bureaucratic log rolling on this?

**Comment by sideshowbarker** [comment]
Yeah we should have a real license both in this file here and at https://github.com/w3c/web-platform-tests/blob/master/LICENSE

Assigning @wseltzer and @plehegar as reviewers for this PR so we can iterate on it here (for one thing I think it needs to be updated to include the Beihang host in the copyright statement, and it seems like  the date in the copyright statement also needs to be made into a range).

When we are done here and get it merged, we can open a https://github.com/w3c/web-platform-tests PR and copy the same change over to there.

**Comment by wseltzer** [comment]
Who suggested this change? I don't think this is the right license

**Comment by sideshowbarker** [comment]
> Who suggested this change? I don't think this is the right license

@cvrebert raised the PR and [said](https://github.com/w3c/csswg-test/pull/1091#issue-159714210):

> I've been told that the `LICENSE` file should contain actual copyright & license text before I can send additional PRs, hence this PR that copies in the relevant legalese from the webpages.

So I am pretty sure he just needs *some* content in the [LICENSE file](https://github.com/w3c/csswg-test/blob/master/LICENSE) (other than a link to content elsewhere) but isn’t intending to propose what the exact text of it is.

So once we decide what the exact actual content should be, we can push a change to this PR branch that just overwrites the proposed change @cvrebert made here, which I think was just intended as a concrete proposal to start from.

**Comment by sideshowbarker** [comment]
> I don't think this is the right license

The current LICENSE file contains a link to http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html and I believe @cvrebert just copied content over from there but I’ve not checked to confirm that.

Regardless, it seems like what we want here is some plain-text formulation of http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html

**Comment by cvrebert** [comment]
> The current LICENSE file contains a link to http://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html and I believe @cvrebert just copied content over from there but I’ve not checked to confirm that.

Correct. This was intended to be a faithful plaintext copy of the webpage.

> So I am pretty sure he just needs some content in the LICENSE file (other than a link to content elsewhere) but isn’t intending to propose what the exact text of it is.

Also correct. This PR used the text from the webpage merely since that's the status quo.

**Comment by cvrebert** [comment]
More precisely, a copy of the license webpages that said webpage links to:
* https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html
* https://www.w3.org/Consortium/Legal/2008/04-testsuite-license.html

**Comment by wseltzer** [comment]
Sorry,  I should have been clearer in my question. @cvrebert , why do we think it is important that the license be copied to this directory rather than referenced from it? After all, references are better for updates (such as the addition of all W3C hosts to the copyright statement as noted missing above).

**Comment by cvrebert** [comment]
@wseltzer Because a license is an agreement between a project maintainer and downstream. It should be spelled out and concrete--not linked to something that can be changed and which is separate from the code.
You wouldn't have a lease agreement on a web page where the terms can be changed without notice.

**Comment by annevk** [comment]
@wseltzer I'd appreciate if you could give this some priority. @cvrebert is a valued contributor to many standards projects. Let's sort this out.

**Comment by wseltzer** [comment]
Thanks for the ping. I created a markdown version of the complete dual-license package. 
https://github.com/w3c/licenses/blob/master/TEST-LICENSE.md that you can add to this repo.

**Comment by wseltzer** [comment]
Offered as https://github.com/w3c/csswg-test/pull/1158 alternative

**Comment by sideshowbarker** [comment]
Superseded by https://github.com/w3c/csswg-test/commit/67b0130943887beb9dac4880161ec579669d3cd6

https://github.com/w3c/csswg-test/blob/master/LICENSE.md

**Comment by cvrebert** [comment]
Super. Thanks folks!

**Comment by annevk** [comment]
Excellent 😊

**Comment by plehegar** [comment]
Thank you Wendy!

**Pull request closed without merging**
