### PR TITLE
[css-ui-3] Add tests for the resize property

### PR DESCRIPTION
**Pull request by frivoal**
Not a whole lot of automated tests in this Pull Request, but I think we're going to have to live with this due to the nature of the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1193)

### CODE REVIEW

**Review by fantasai — COMMENTED** [review]
You misspelled resize in all of the titles.

**Review by fantasai — CHANGES_REQUESTED** [review]
* Need to fix typos in titles.
* It would be better if all of the tests used a blue (or orange) box instead of the sheep. This way the tester doesn't need to be distracted by how the image resizes (e.g. aspect ratio skews or not, whether the sheep adjusts with the size of the iframe boundaries or not, etc).
* The verification in resize-015 needs to check whether the width/height was actually changed -- they need to be not equal to the sizes set in the CSS.
* resize-15, resize-016, etc. need their titles updated to reflect what's being tested.
* resize-016, resize-17 need to test that the non-resizable dimension is not resizable.
* since we can, resize-018 should check that the size is actually maintained by storing the size and then comparing it before/after resetting
* you're missing tests that include min/max-width/height (but that can be a separate PR, just mentioning it here)

**Comment by frivoal** [comment]
@fantasai 

All the issues you reported should be addressed now, including the missing tests for min/max-width/height.

The missing `<g id='testmeta'>` that syncbot is complaining about is not as far as I know an actuall requirement we have, and we already have svg images without it, so I'm ignoring this warning. If I should not ignore it, is there documentation of what I'm supposed to put there?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5386; please continue all discussion there.

**Pull request closed without merging**
