### PR TITLE
Travis CI build: Cache tools repos

### LINKED ISSUE #861: Travis build: Extract tool tarballs instead of cloning hg repos
Currently, the Travis build [tries to `hg clone` 2 tool repos](https://github.com/w3c/csswg-test/blob/39770a08bd3add1fe14dd2f203c4592cb4bedea4/tools/travis/build.py#L20), which tends to cause [Travis errors or timeouts](https://travis-ci.org/w3c/csswg-test/builds/80201151) due to how long the full clones take and network unreliability. It would be much faster to just download and extract the repos' tarballs (e.g. https://hg.csswg.org/dev/apiclient/archive/tip.tar.gz ) instead.
CC: @Ms2ger

### PR DESCRIPTION
**Pull request by cvrebert**
Docs: http://docs.travis-ci.com/user/caching/#Arbitrary-directories
Closes #861.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/908)

### CODE REVIEW

**Comment by cvrebert** [comment]
@Ms2ger @indygreg LGTY?

**Comment by gsnedders** [comment]
@Ms2ger can you have a look at why Travis is failing here? I can't immediately work out why?

**Comment by gsnedders** [comment]
Um, uh. Looking again, given the fix… That's really obvious. Duh.

LGTM. :+1:

**Comment by gsnedders** [comment]
Hmm, weird. This broke Travis. See https://travis-ci.org/w3c/csswg-test/builds/85206242

**Comment by gsnedders** [comment]
```
abort: no repository found in '/home/travis/build/w3c/csswg-test/tools/apiclient' (.hg not found)!
```

This makes it sound like, uh, the hg directory got nuked somewhere, somehow.

**Comment by cvrebert** [comment]
Taking another crack at this: https://travis-ci.org/w3c/csswg-test/builds/85225943
This variation looks for the `.hg` directories specifically.

**Comment by gsnedders** [comment]
I wonder if Travis is doing something whacky to it? If it is, it means this is all pointless. <_<

**Comment by cvrebert** [comment]
Success: https://travis-ci.org/w3c/csswg-test/builds/85227540
Now to force a rebuild and confirm that the cache gets used...

**Comment by cvrebert** [comment]
Ok, the caching works properly, there's just an unrelated error in `add_changeset`, which doesn't seem to be written to take into account the possibility of restarted Travis builds.

**Comment by cvrebert** [comment]
@gsnedders Relatedly, is there a particular reason the build checks out the Template-Python SVN repo instead of installing [your PyPI packaged version](https://pypi.python.org/pypi/Template-Python/0.1.post1) ?

**Comment by indygreg** [comment]
I'm not sure if you expect files in the working copy to get mutated, but I typically recommend the following for robustly updating a working copy in an automated environment:

1. hg pull -r <rev or branch name>
2. hg --config extensions.purge= purge --all
3. hg up -C -r <rev or branch name>

purge will remove untracked and ignored files. up -C will discard uncommitted changes on update. The two of them together should protect you against any unwanted modifications from a previous build/environment influencing subsequent operations. i.e. it's more deterministic.

**Comment by indygreg** [comment]
GitHub silently swallowed some of the comment without warning me first. -r requires an argument.

**Comment by Ms2ger** [comment]
@cvrebert https://github.com/jgraham/css-test-build/issues/1

**Pull request merged**
