### PR TITLE
Add a test for `offsetWidth`, detached elements.

### PR DESCRIPTION
**Pull request by notriddle**
Test based on bug servo/servo#8240.

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/928)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please get rid of the tabs and format more like:
```js
test(function() {
    // These asserts need to be in this order to trigger a bug in Servo.
    var el = document.createElement("div");
    el.appendChild(document.createTextNode("..."));
    assert_equals(el.offsetWidth, 0, "new element has offset width not equal to zero")
    assert_not_equals(document.getElementById("myDiv"), 0, "element with content has offset width equal to zero");
    document.documentElement.remove();
    assert_equals(el.offsetWidth, 0, "new element has offset width not equal to zero after removing documentElement")
});
```

**Comment by notriddle** [comment]
Fixed @Ms2ger's problems.

**Comment by notriddle** [comment]
Could somebody please review this?

**Comment by Ms2ger** [comment]
@zcorpan r?

**Comment by zcorpan** [comment]
Lgtm

**Pull request merged**
