### PR TITLE
[css-flexbox] fix css-flexbox-img-expand-evenly.html

### PR DESCRIPTION
**Pull request by cbiesinger**
- Path to the image file was incorrect
- Linebreak needs to be removed, see comment in patch

[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/877)

### CODE REVIEW

**Comment by kojiishi** [comment]
"../support" can work locally, but does not work for the test build system. You need to create "support" directory under css-flexbox-1 and have a copy there. Please refer to [comments here](https://github.com/w3c/csswg-test/pull/763#issuecomment-110788894).

**Comment by cbiesinger** [comment]
@kojiishi css-flexbox-1/support already has that file; this was only for the reference... do I need to create css-flexbox-1/reference/support and copy the file there? Or, what is the right way to do this?

**Comment by cbiesinger** [comment]
Other reference files do have .. in their paths:

../css-backgrounds-3/reference/css3-border-image-repeat-stretch-ref.html:      left blue diamond
../css-backgrounds-3/reference/css3-border-image-source-ref.html:      baidu logo at right bottom

../css21/reference/ref-filled-black-96px-square.xht:  <div>Image download support must be enabled</div>

etc

**Comment by plinss** [comment]
The build system follows reference paths and updates the reference links to ensure they work after the build. It does not (currently) follow support paths and fix them up so they all need to be of the form 'support/(filename)'.

**Comment by plinss** [comment]
The build output will be:
test files/
    reference/
    support/

So it's ok for reference files to refer to support files as '../support/(filename)' so long as the same path is valid in the source.

**Comment by cbiesinger** [comment]
Thanks for the explanation! So this pull request should be already correct, then.

**Comment by plinss** [comment]
Yeah, the paths look fine to me.

**Comment by kojiishi** [comment]
I missed that the files are ref files, sorry about that. lgtm

**Pull request merged**
