### PR TITLE
Various cssom improvements.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/w3c/csswg-test/964)

### CODE REVIEW

**Comment by cvrebert** [comment]
This currently has merge conflicts.

**Comment by Ms2ger** [comment]
@cvrebert fixed

**Comment by zcorpan** [comment]
Hmm. I restarted https://travis-ci.org/w3c/csswg-test/builds/102329688 but now it failed. Unclear to me why.

**Comment by zcorpan** [comment]
@Ms2ger can you rebase? (I tried doing so myself but your remote rejected me pushing to this branch.)

**Comment by zcorpan** [comment]
Changes LGTM if Travis is happy. (We need to figure out how colors as specified value should be serialized, but separate from this PR.)

**Pull request merged**
