### PR TITLE
Introduce references for some CSS2.1 syntax tests.

### PR DESCRIPTION
**Pull request by Ms2ger**
This is based on work originally done by Geoffrey Sneddon.

### CODE REVIEW

**Comment by gsnedders** [comment]
Along with that lint, guess it's worthwhile updating my email to something that works. (`me@gsnedders.com`, probably.)

**Comment by gsnedders** [comment]
https://lists.w3.org/Archives/Public/public-css-testsuite/2010Sep/0030.html is what I was guessing this is based on, but this only has those that use `filler-text-below-green.xht` and not the three other refs there.

**Comment by Ms2ger** [comment]
Yeah, there's more where this came from, but given the reception last time, I didn't want to put in the work before I knew it'd be merged.

**Comment by gsnedders** [comment]
Oh, Opera had *way* more done internally after that email — that email just covered the top four most common screenshots. I just never bothered pushing it anywhere, given everyone else didn't want the whole test suite in their regression suite because of the execution time.

**Pull request merged**
