### PR TITLE
[css-logical-properties-1] Add test case margin{-block,-inline}

### PR DESCRIPTION
**Pull request by axinging**
Spec is here: https://drafts.csswg.org/css-logical-props-1/#logical-prop.
This depends on https://github.com/w3c/csswg-test/pull/1165.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/csswg-test/1170)

### CODE REVIEW

**Comment by axinging** [comment]
@rune-opera @cbiesinger, PTAL.

BTW, it seems Firefox can not get  marginBlockStart with getComputedStyle:
getComputedStyle(document.getElementById("div_htb")).marginBlockStart ==>return "".
Sample code is here: https://jsfiddle.net/xuvy4ago/

Any idea about his?

**Comment by cbiesinger** [comment]
@dbaron see comment above re Gecko computed style for margin-block-start

**Comment by dbaron** [comment]
We [deferred implementing it until later](https://bugzilla.mozilla.org/show_bug.cgi?id=649142#c31) and [still haven't fixed the followup bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1116638).  But it's not clear that we *should* implement it unless there's a clear spec for it.  For example, https://github.com/w3c/csswg-drafts/issues/384 is currently open, and would lead to significantly different behavior depending on the response.

**Comment by mrego** [comment]
Actually w3c/csswg-drafts#384 is closed and the spec has been updated:
https://drafts.csswg.org/cssom/#resolved-value

According to it "*the resolved value is the used value*" like for the other properties.

**Comment by cbiesinger** [comment]
OK -- based on that:
@axinging, can you add tests for percentages that make sure that a) they're resolved against the right axis and b) that the computed style has the resolved value, not the used value?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/5284; please continue all discussion there.

**Pull request closed without merging**
