### PR TITLE
Test that insanely large min-width media query is false

### PR DESCRIPTION
**Pull request by cvrebert**
Apologies in advance for any rookie mistakes I've made. This is my first time trying to submit one of these tests.

See also:
* http://wkbug.com/141533
* http://crbug.com/375574
* https://github.com/twbs/bootstrap/issues/13632

### CODE REVIEW

**Comment by frivoal** [comment]
Thanks for submitting a test. Rookie or not, your test looks pretty good.

I think you're basing this requirement for clamping on this sentence: "In cases where the used length cannot be supported, user agents must approximate it in the actual value". It is a bit ambiguous, but I agree with you that clamping, not overflowing, is the desirable behavior. Having an infinity value would be OK as well, but your test would behave correctly in that case as well, so that's fine.

Also, even if a UA actually did support such large numbers without clamping, it is reasonable to expect that no matter what the future holds in terms of new devices, nobody will build a CSS capable device with a screen about 2646km meant to be viewed at arms length distance, so I think we're safe there as well :)

Before I approve the test and merge, there's a few small things that I would appreciate if you could change:

1) Instead of making your own reference file, could you use mediaqueries-3/ref.html instead and adjust your test to match? When reviewing test results manually, it is much easier and faster to evaluate multiple tests that look exactly the same when they succeed, rather than similar but different passing conditions.

2) Could you add a link to http://www.w3.org/TR/mediaqueries-4/#width in addition to the media-queries 3 one? This way it will be picked up by the test suite of both specs, and since media queries 4 is the one that's a work in progress, there a bit higher chance that people will look there.

3) Without changing the behavior of your test, maybe you could tweak the assert sentence a bit, so that instead of "[...] must be clamped instead of [...]", you could say something like "[...]must be clamped, rounded to infinity, or approximated, but not [...]".

**Comment by cvrebert** [comment]
@frivoal Thanks for the rapid response!

> 1) Instead of making your own reference file, could you use mediaqueries-3/ref.html instead and adjust your test to match?

Done.

> 2) Could you add a link to http://www.w3.org/TR/mediaqueries-4/#width in addition to the media-queries 3 one?

Done.

> 3) Without changing the behavior of your test, maybe you could tweak the assert sentence a bit

Done.

**Comment by frivoal** [comment]
Thanks, Merged.

I hope you'll send many more tests our way.

By the way, I saw that your earlier commits used html, and you only switched to xhtml when the syncbot complained about syntax problems. Both html and xhtml are fine, so use which ever you want (but if you use html, use .html, not .xht for the file name).

**Comment by cvrebert** [comment]
Yeah, the contributing docs aren't terribly clear about that. I'll see about improving that aspect of those docs.

**Comment by frivoal** [comment]
That be great, thanks. If you do and you don't get any reaction, ping me and I'll find the right people to nag to get it merged.

**Pull request merged**
